export type {
  ArchivoData,
  AreaActiva,
  AreaDistribucionData,
  AsignacionDetalle,
  CreateTramiteData,
  ExpedienteAntecedente,
  ExpedienteArchivo,
  ExpedienteCreateData,
  ExpedienteDetail,
  ExpedienteDetailResponse,
  ExpedienteItem,
  ExpedienteListResponse,
  HistorialEstadoGlobal,
  PaginacionData,
  ParticipanteDetalle,
  PeriodoDetalle,
  RespuestaDetalle,
  SolicitudDetail,
  SolicitudDetailResponse,
  SolicitudItem,
  SolicitudListResponse,
  TipoDocumento,
} from "./tramite.schema";
export {
  ArchivoSchema,
  AreaActivaSchema,
  AreaDistribucionSchema,
  CreateTramiteSchema,
  ExpedienteAntecedenteSchema,
  ExpedienteArchivoSchema,
  ExpedienteCreateSchema,
  ExpedienteDetailResponseSchema,
  ExpedienteDetailSchema,
  ExpedienteItemSchema,
  ExpedienteListResponseSchema,
  HistorialEstadoGlobalSchema,
  PaginacionSchema,
  ParticipanteDetalleSchema,
  PeriodoDetalleSchema,
  RespuestaDetalleSchema,
  SolicitudDetailResponseSchema,
  SolicitudDetailSchema,
  SolicitudItemSchema,
  SolicitudListResponseSchema,
  TipoDocumentoSchema,
} from "./tramite.schema";
// ── Trazabilidad schemas (M5) ─────────────────────────────────────────────────
export type {
  AsignacionTrazabilidad,
  HistorialEstadoGlobalTrazabilidad,
  ParticipanteTrazabilidad,
  PeriodoEstadoHistorial,
  PeriodoTrazabilidad,
  RespuestaTrazabilidad,
  SolicitudTrazabilidad,
  SolicitudTrazabilidadResponse,
  TimelineEvent,
} from "./trazabilidad.schema";
export {
  AsignacionTrazabilidadSchema,
  HistorialEstadoGlobalTrazabilidadSchema,
  ParticipanteTrazabilidadSchema,
  PeriodoEstadoHistorialSchema,
  PeriodoTrazabilidadSchema,
  RespuestaTrazabilidadSchema,
  SolicitudTrazabilidadResponseSchema,
  SolicitudTrazabilidadSchema,
  TimelineEventSchema,
} from "./trazabilidad.schema";
