# Generated by Django 5.2.11 on 2026-09-19 07:15
# Manual migration: aligns 0001_initial state to current Usuario model.

import uuid
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        # ── Persona ──────────────────────────────────────────────────────────────
        migrations.CreateModel(
            name="Persona",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creacion")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Ultima actualizacion")),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                ("apellidos", models.CharField(max_length=255, verbose_name="Apellidos")),
                ("tipo_documento", models.CharField(choices=[("DNI", "DNI"), ("CE", "Carnet de Extranjeria"), ("PAS", "Pasaporte")], max_length=3, verbose_name="Tipo de documento")),
                ("numero_documento", models.CharField(max_length=20, verbose_name="Numero de documento")),
                ("genero", models.CharField(choices=[("M", "Masculino"), ("F", "Femenino")], max_length=1, verbose_name="Genero")),
                ("telefono", models.CharField(blank=True, max_length=9, null=True, verbose_name="Telefono")),
                ("whatsapp", models.CharField(blank=True, max_length=9, null=True, verbose_name="WhatsApp")),
                ("contacto_emergencia_nombre", models.CharField(blank=True, max_length=120, null=True, verbose_name="Nombre de contacto de emergencia")),
                ("contacto_emergencia_telefono", models.CharField(blank=True, max_length=9, null=True, verbose_name="Telefono de emergencia")),
                ("aseguradora_nombre", models.CharField(blank=True, max_length=255, null=True, verbose_name="Nombre de aseguradora")),
                ("aseguradora_numero_poliza", models.CharField(blank=True, max_length=50, null=True, verbose_name="Numero de poliza")),
            ],
            options={"verbose_name": "Persona", "verbose_name_plural": "Personas"},
        ),
        # ── PersonaAceptacion ─────────────────────────────────────────────────
        migrations.CreateModel(
            name="PersonaAceptacion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creacion")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Ultima actualizacion")),
                ("tipo_aceptacion", models.CharField(choices=[("BASES", "Bases del evento"), ("APTITUD_FISICA", "Certificado de aptitud fisica"), ("IMAGEN", "Uso de imagen")], max_length=30, verbose_name="Tipo de aceptacion")),
                ("documento_version", models.CharField(blank=True, help_text="Ej: BASES-SF26-2026-09-06", max_length=50, null=True, verbose_name="Version del documento")),
                ("aceptado_en", models.DateTimeField(verbose_name="Fecha de aceptacion")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="Direccion IP")),
                ("user_agent", models.CharField(blank=True, max_length=500, null=True, verbose_name="User Agent")),
                ("persona", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="aceptaciones", to="usuarios.persona", verbose_name="Persona")),
            ],
            options={"ordering": ["-aceptado_en"], "verbose_name": "Aceptacion de Persona", "verbose_name_plural": "Aceptaciones de Personas"},
        ),
        # ── Unique constraint on Persona ──────────────────────────────────────
        migrations.AddConstraint(
            model_name="persona",
            constraint=models.UniqueConstraint(fields=("tipo_documento", "numero_documento"), name="unique_tipo_numero_documento"),
        ),
        # ── Usuario.persona_fk (nullable initially, will be made NOT NULL in next migration) ──
        migrations.AddField(
            model_name="usuario",
            name="persona_fk",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="usuario", to="usuarios.persona", verbose_name="Persona asociada"),
        ),
        # ── Align username field (no more DNI validator, uses username_validator) ──
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(help_text="Nombre de usuario para login (letras minusculas, numeros, puntos, guiones bajos o guiones).", max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code="invalid_username", message="El nombre de usuario debe contener solo letras minusculas, numeros, puntos, guiones bajos o guiones.", regex="^[a-z0-9._-]+$")], verbose_name="Nombre de usuario"),
        ),
        # ── Align dni field (legacy, nullable) ───────────────────────────────
        migrations.AlterField(
            model_name="usuario",
            name="dni",
            field=models.CharField(blank=True, help_text="DNI legacy -- la identidad civil ahora vive en Persona.", max_length=8, null=True, unique=True, verbose_name="DNI legacy"),
        ),
    ]
