# Generated by Django 5.2.11 on 2026-09-19 07:20
# Enforce persona_fk NOT NULL on Usuario.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_add_persona_and_align_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="persona_fk",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuario",
                to="usuarios.persona",
                verbose_name="Persona asociada",
                null=False,
                blank=False,
            ),
        ),
    ]
