# Generated by Django 5.2.11 on 2026-09-19 06:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_enforce_persona_fk_not_null"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalperfilingeniero",
            name="capitulo",
        ),
        migrations.RemoveField(
            model_name="historicalespecialidadingeniero",
            name="capitulo",
        ),
        migrations.RemoveField(
            model_name="especialidadingeniero",
            name="capitulo",
        ),
        migrations.RemoveField(
            model_name="perfilingeniero",
            name="capitulo",
        ),
        migrations.RemoveField(
            model_name="perfilingeniero",
            name="especialidad",
        ),
        migrations.RemoveField(
            model_name="historicalperfilingeniero",
            name="especialidad",
        ),
        migrations.DeleteModel(
            name="EspecialidadRevision",
        ),
        migrations.RemoveField(
            model_name="historicalcapitulo",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalespecialidadingeniero",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalespecialidadrevision",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalingenierohabilitacion",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalingenierohabilitacion",
            name="perfil_ingeniero",
        ),
        migrations.RemoveField(
            model_name="historicalperfilingeniero",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalperfilingeniero",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="ingenierohabilitacion",
            name="perfil_ingeniero",
        ),
        migrations.RemoveField(
            model_name="perfilingeniero",
            name="usuario",
        ),
        migrations.AlterModelOptions(
            name="personaaceptacion",
            options={
                "ordering": ["-aceptado_en"],
                "verbose_name": "Aceptación de Persona",
                "verbose_name_plural": "Aceptaciones de Personas",
            },
        ),
        migrations.RemoveField(
            model_name="historicalusuario",
            name="apellidos",
        ),
        migrations.RemoveField(
            model_name="historicalusuario",
            name="nombres",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="apellidos",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="nombres",
        ),
        migrations.AddField(
            model_name="historicalusuario",
            name="persona_fk",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="usuarios.persona",
                verbose_name="Persona asociada",
            ),
        ),
        migrations.AlterField(
            model_name="historicalusuario",
            name="dni",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="DNI legacy — la identidad civil ahora vive en Persona.",
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_dni",
                        message="El DNI debe contener exactamente 8 dígitos numéricos.",
                        regex="^\\d{8}$",
                    )
                ],
                verbose_name="DNI legacy",
            ),
        ),
        migrations.AlterField(
            model_name="historicalusuario",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Correo electrónico",
            ),
        ),
        migrations.AlterField(
            model_name="historicalusuario",
            name="username",
            field=models.CharField(
                db_index=True,
                help_text="Nombre de usuario para login (letras minúsculas, números, puntos, guiones bajos o guiones).",
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="El nombre de usuario debe contener solo letras minúsculas, números, puntos, guiones bajos o guiones.",
                        regex="^[a-z0-9._-]+$",
                    )
                ],
                verbose_name="Nombre de usuario",
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="aseguradora_numero_poliza",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Número de póliza"
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="contacto_emergencia_telefono",
            field=models.CharField(
                blank=True,
                max_length=9,
                null=True,
                verbose_name="Teléfono de emergencia",
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="genero",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Femenino")],
                max_length=1,
                verbose_name="Género",
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="numero_documento",
            field=models.CharField(max_length=20, verbose_name="Número de documento"),
        ),
        migrations.AlterField(
            model_name="persona",
            name="telefono",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Teléfono"
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("DNI", "DNI"),
                    ("CE", "Carnet de Extranjería"),
                    ("PAS", "Pasaporte"),
                ],
                max_length=3,
                verbose_name="Tipo de documento",
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última actualización"
            ),
        ),
        migrations.AlterField(
            model_name="personaaceptacion",
            name="aceptado_en",
            field=models.DateTimeField(verbose_name="Fecha de aceptación"),
        ),
        migrations.AlterField(
            model_name="personaaceptacion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="personaaceptacion",
            name="documento_version",
            field=models.CharField(
                blank=True,
                help_text="Ej: BASES-SF26-2026-09-06",
                max_length=50,
                null=True,
                verbose_name="Versión del documento",
            ),
        ),
        migrations.AlterField(
            model_name="personaaceptacion",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="Dirección IP"
            ),
        ),
        migrations.AlterField(
            model_name="personaaceptacion",
            name="tipo_aceptacion",
            field=models.CharField(
                choices=[
                    ("BASES", "Bases del evento"),
                    ("APTITUD_FISICA", "Certificado de aptitud física"),
                    ("IMAGEN", "Uso de imagen"),
                ],
                max_length=30,
                verbose_name="Tipo de aceptación",
            ),
        ),
        migrations.AlterField(
            model_name="personaaceptacion",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última actualización"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="dni",
            field=models.CharField(
                blank=True,
                help_text="DNI legacy — la identidad civil ahora vive en Persona.",
                max_length=8,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_dni",
                        message="El DNI debe contener exactamente 8 dígitos numéricos.",
                        regex="^\\d{8}$",
                    )
                ],
                verbose_name="DNI legacy",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Correo electrónico",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(
                help_text="Nombre de usuario para login (letras minúsculas, números, puntos, guiones bajos o guiones).",
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="El nombre de usuario debe contener solo letras minúsculas, números, puntos, guiones bajos o guiones.",
                        regex="^[a-z0-9._-]+$",
                    )
                ],
                verbose_name="Nombre de usuario",
            ),
        ),
        migrations.DeleteModel(
            name="Capitulo",
        ),
        migrations.DeleteModel(
            name="EspecialidadIngeniero",
        ),
        migrations.DeleteModel(
            name="HistoricalCapitulo",
        ),
        migrations.DeleteModel(
            name="HistoricalEspecialidadIngeniero",
        ),
        migrations.DeleteModel(
            name="HistoricalEspecialidadRevision",
        ),
        migrations.DeleteModel(
            name="HistoricalIngenieroHabilitacion",
        ),
        migrations.DeleteModel(
            name="HistoricalPerfilIngeniero",
        ),
        migrations.DeleteModel(
            name="IngenieroHabilitacion",
        ),
        migrations.DeleteModel(
            name="PerfilIngeniero",
        ),
    ]
