# Generated by Django 5.2.11 on 2026-09-22 17:08

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_remove_historicalperfilingeniero_capitulo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPersona",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI"),
                            ("CE", "Carnet de Extranjería"),
                            ("PAS", "Pasaporte"),
                        ],
                        max_length=3,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(max_length=20, verbose_name="Número de documento"),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")],
                        max_length=1,
                        verbose_name="Género",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "contacto_emergencia_nombre",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Nombre de contacto de emergencia",
                    ),
                ),
                (
                    "contacto_emergencia_telefono",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="Teléfono de emergencia",
                    ),
                ),
                (
                    "aseguradora_nombre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre de aseguradora",
                    ),
                ),
                (
                    "aseguradora_numero_poliza",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número de póliza",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Persona",
                "verbose_name_plural": "historical Personas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPersonaAceptacion",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo_aceptacion",
                    models.CharField(
                        choices=[
                            ("BASES", "Bases del evento"),
                            ("APTITUD_FISICA", "Certificado de aptitud física"),
                            ("IMAGEN", "Uso de imagen"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de aceptación",
                    ),
                ),
                (
                    "documento_version",
                    models.CharField(
                        blank=True,
                        help_text="Ej: BASES-SF26-2026-09-06",
                        max_length=50,
                        null=True,
                        verbose_name="Versión del documento",
                    ),
                ),
                (
                    "aceptado_en",
                    models.DateTimeField(verbose_name="Fecha de aceptación"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="User Agent"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="usuarios.persona",
                        verbose_name="Persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Aceptación de Persona",
                "verbose_name_plural": "historical Aceptaciones de Personas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
