# Generated by Django 5.2.12 on 2026-10-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_historicalpersona_historicalpersonaaceptacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personaaceptacion",
            name="persona",
        ),
        migrations.AddField(
            model_name="historicalpersona",
            name="acepto_aptitud_fisica",
            field=models.BooleanField(
                default=False, verbose_name="Aceptó certificado de aptitud física"
            ),
        ),
        migrations.AddField(
            model_name="historicalpersona",
            name="acepto_bases",
            field=models.BooleanField(
                default=False, verbose_name="Aceptó bases del evento"
            ),
        ),
        migrations.AddField(
            model_name="historicalpersona",
            name="acepto_imagen",
            field=models.BooleanField(
                default=False, verbose_name="Aceptó uso de imagen"
            ),
        ),
        migrations.AddField(
            model_name="persona",
            name="acepto_aptitud_fisica",
            field=models.BooleanField(
                default=False, verbose_name="Aceptó certificado de aptitud física"
            ),
        ),
        migrations.AddField(
            model_name="persona",
            name="acepto_bases",
            field=models.BooleanField(
                default=False, verbose_name="Aceptó bases del evento"
            ),
        ),
        migrations.AddField(
            model_name="persona",
            name="acepto_imagen",
            field=models.BooleanField(
                default=False, verbose_name="Aceptó uso de imagen"
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalPersonaAceptacion",
        ),
        migrations.DeleteModel(
            name="PersonaAceptacion",
        ),
    ]
