# Generated by Django 5.2.12 on 2026-09-21 22:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inscripciones", "0005_remove_uq_equipo_inscripcion_disciplina"),
    ]

    operations = [
        migrations.CreateModel(
            name="IzipayTransaccion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "proveedor",
                    models.CharField(
                        default="IZIPAY",
                        editable=False,
                        max_length=20,
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Transaction ID Izipay",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=100, verbose_name="Numero de orden"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="PEN", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EXITO", "Exito"),
                            ("FALLIDO", "Fallido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "response_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Codigo de respuesta",
                    ),
                ),
                (
                    "response_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de respuesta"
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Metodo de pago",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos"
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transacciones_izipay",
                        to="inscripciones.inscripcion",
                        verbose_name="Inscripcion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaccion Izipay",
                "verbose_name_plural": "Transacciones Izipay",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["inscripcion", "status"], name="ix_izipay_insc_status"
                    ),
                    models.Index(
                        fields=["inscripcion", "created_at"],
                        name="ix_izipay_insc_created",
                    ),
                ],
            },
        ),
    ]
