# Generated by Django 5.2.11 on 2026-09-22 17:08

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscripciones", "0007_historicalcategoria_historicaldisciplina_and_more"),
        ("pagos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalIzipayTransaccion",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "proveedor",
                    models.CharField(
                        default="IZIPAY",
                        editable=False,
                        max_length=20,
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        verbose_name="Transaction ID Izipay",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=100, verbose_name="Numero de orden"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="PEN", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EXITO", "Exito"),
                            ("FALLIDO", "Fallido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "response_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Codigo de respuesta",
                    ),
                ),
                (
                    "response_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de respuesta"
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Metodo de pago",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inscripciones.inscripcion",
                        verbose_name="Inscripcion",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Transaccion Izipay",
                "verbose_name_plural": "historical Transacciones Izipay",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
