# Generated by Django 5.2.11 on 2026-09-19 05:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0002_add_persona_and_align_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre de disciplina"
                    ),
                ),
                (
                    "sigla",
                    models.CharField(max_length=20, unique=True, verbose_name="Sigla"),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("X", "Mixto")],
                        max_length=1,
                        verbose_name="Modalidad",
                    ),
                ),
                (
                    "min_jugadores",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Null = sin límite inferior",
                        null=True,
                        verbose_name="Mínimo de jugadores",
                    ),
                ),
                (
                    "max_jugadores",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Null = sin límite superior",
                        null=True,
                        verbose_name="Máximo de jugadores",
                    ),
                ),
                (
                    "esta_activa",
                    models.BooleanField(default=True, verbose_name="¿Está activa?"),
                ),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del evento"),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de fin")),
                (
                    "esta_activo",
                    models.BooleanField(default=True, verbose_name="¿Está activo?"),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Paquete",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre del paquete"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "cantidad_maxima_participantes",
                    models.PositiveIntegerField(
                        help_text="Límite total de personas únicas en el paquete",
                        verbose_name="Cantidad máxima de participantes",
                    ),
                ),
                (
                    "precio_regular",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Precio regular",
                    ),
                ),
                (
                    "precio_promocional",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Precio promocional",
                    ),
                ),
                ("valido_desde", models.DateField(verbose_name="Válido desde")),
                ("valido_hasta", models.DateField(verbose_name="Válido hasta")),
                (
                    "esta_activo",
                    models.BooleanField(default=True, verbose_name="¿Está activo?"),
                ),
            ],
            options={
                "verbose_name": "Paquete",
                "verbose_name_plural": "Paquetes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, verbose_name="Nombre de categoría"),
                ),
                (
                    "anio_minimo",
                    models.PositiveIntegerField(
                        verbose_name="Año mínimo de nacimiento"
                    ),
                ),
                (
                    "anio_maximo",
                    models.PositiveIntegerField(
                        verbose_name="Año máximo de nacimiento"
                    ),
                ),
                (
                    "esta_activa",
                    models.BooleanField(default=True, verbose_name="¿Está activa?"),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categorias",
                        to="inscripciones.disciplina",
                        verbose_name="Disciplina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["disciplina", "anio_minimo"],
            },
        ),
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "promocion",
                    models.CharField(
                        help_text="Ej. '2002'", max_length=10, verbose_name="Promoción"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("RECIBIDA", "Recibida"),
                            ("EN_REVISION", "En revision"),
                            ("OBSERVADA", "Observada"),
                            ("VALIDADA", "Validada"),
                            ("PAGO_PENDIENTE", "Pago pendiente"),
                            ("PAGADA", "Pagada"),
                            ("CONFIRMADA", "Confirmada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="RECIBIDA",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observacion",
                    models.TextField(
                        blank=True,
                        help_text="Observación del Comité",
                        null=True,
                        verbose_name="Observación",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscripciones",
                        to="inscripciones.evento",
                        verbose_name="Evento",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscripciones_responsable",
                        to="usuarios.persona",
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "paquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscripciones",
                        to="inscripciones.paquete",
                        verbose_name="Paquete",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripción",
                "verbose_name_plural": "Inscripciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EquipoInscrito",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=120, verbose_name="Nombre del equipo"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipos_inscritos",
                        to="inscripciones.categoria",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipos_inscritos",
                        to="inscripciones.disciplina",
                        verbose_name="Disciplina",
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipos",
                        to="inscripciones.inscripcion",
                        verbose_name="Inscripción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo inscrito",
                "verbose_name_plural": "Equipos inscritos",
                "ordering": ["inscripcion", "disciplina"],
            },
        ),
        migrations.CreateModel(
            name="InscripcionDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegados",
                        to="inscripciones.inscripcion",
                        verbose_name="Inscripción",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegaciones",
                        to="usuarios.persona",
                        verbose_name="Delegado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delegado de inscripción",
                "verbose_name_plural": "Delegados de inscripción",
            },
        ),
        migrations.CreateModel(
            name="PaqueteDisciplina",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paquete_disciplinas",
                        to="inscripciones.disciplina",
                        verbose_name="Disciplina",
                    ),
                ),
                (
                    "paquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paquete_disciplinas",
                        to="inscripciones.paquete",
                        verbose_name="Paquete",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplina de paquete",
                "verbose_name_plural": "Disciplinas de paquete",
            },
        ),
        migrations.CreateModel(
            name="ParticipacionDisciplina",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participaciones",
                        to="inscripciones.disciplina",
                        verbose_name="Disciplina",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participaciones",
                        to="inscripciones.equipoinscrito",
                        verbose_name="Equipo",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participaciones",
                        to="inscripciones.evento",
                        verbose_name="Evento",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participaciones",
                        to="usuarios.persona",
                        verbose_name="Persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participación en disciplina",
                "verbose_name_plural": "Participaciones en disciplinas",
                "ordering": ["evento", "disciplina", "persona"],
            },
        ),
        migrations.CreateModel(
            name="ParticipanteInscripcion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("JUGADOR", "Jugador"),
                            ("CAPITAN", "Capitan"),
                            ("DELEGADO", "Delegado"),
                        ],
                        default="JUGADOR",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "talle_camiseta",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ],
                        max_length=5,
                        null=True,
                        verbose_name="Talle de camiseta",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participantes_inscripcion",
                        to="inscripciones.equipoinscrito",
                        verbose_name="Equipo",
                    ),
                ),
                (
                    "participacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participantes",
                        to="inscripciones.participaciondisciplina",
                        verbose_name="Participación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante de inscripción",
                "verbose_name_plural": "Participantes de inscripción",
                "ordering": ["participacion", "equipo"],
            },
        ),
        migrations.AddConstraint(
            model_name="categoria",
            constraint=models.UniqueConstraint(
                fields=("disciplina", "nombre"),
                name="unique_disciplina_categoria_nombre",
            ),
        ),
        migrations.AddConstraint(
            model_name="equipoinscrito",
            constraint=models.UniqueConstraint(
                fields=("inscripcion", "disciplina"),
                name="uq_equipo_inscripcion_disciplina",
            ),
        ),
        migrations.AddConstraint(
            model_name="inscripciondelegado",
            constraint=models.UniqueConstraint(
                fields=("inscripcion",), name="unique_delegado_por_inscripcion"
            ),
        ),
        migrations.AddConstraint(
            model_name="paquetedisciplina",
            constraint=models.UniqueConstraint(
                fields=("paquete", "disciplina"), name="unique_paquete_disciplina"
            ),
        ),
        migrations.AddConstraint(
            model_name="participaciondisciplina",
            constraint=models.UniqueConstraint(
                fields=("evento", "disciplina", "persona"),
                name="unique_persona_disciplina_evento",
            ),
        ),
    ]
