# Generated by Django 5.2.11 on 2026-09-19 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscripciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promocion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "anio",
                    models.PositiveIntegerField(
                        help_text="Año de graduación (e.g., 2002)",
                        unique=True,
                        verbose_name="Año de promoción",
                    ),
                ),
                (
                    "colegio",
                    models.CharField(
                        choices=[("sjb", "San José"), ("ma", "María Auxiliadora")],
                        default="ma",
                        help_text="SJB (San José) o MA (María Auxiliadora)",
                        max_length=3,
                        verbose_name="Colegio",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Promoción 2002'",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Si está activa para nuevas inscripciones",
                        verbose_name="Activa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promoción",
                "verbose_name_plural": "Promociones",
                "ordering": ["-anio"],
            },
        ),
        migrations.AddField(
            model_name="inscripcion",
            name="fusion_promocion",
            field=models.ForeignKey(
                blank=True,
                help_text="Promoción de fusión (opcional, para equipos combinados)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inscripciones_fusion",
                to="inscripciones.promocion",
                verbose_name="Promoción de fusión",
            ),
        ),
        migrations.AlterField(
            model_name="inscripcion",
            name="promocion",
            field=models.ForeignKey(
                help_text="Año de promoción del equipo/responsable",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inscripciones",
                to="inscripciones.promocion",
                verbose_name="Promoción",
            ),
        ),
    ]
