# Generated by Django 5.2.11 on 2026-09-19 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscripciones", "0002_promocion_inscripcion_fusion_promocion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipoinscrito",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipos_inscritos",
                to="inscripciones.categoria",
                verbose_name="Categoría",
            ),
        ),
    ]
