# Generated by Django 5.2.11 on 2026-09-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscripciones", "0003_alter_equipoinscrito_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="paquete",
            name="cantidad_disciplinas_requeridas",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Número de disciplinas que el usuario debe seleccionar (para modo ELEGIBLE).",
                null=True,
                verbose_name="Cantidad de disciplinas requeridas",
            ),
        ),
        migrations.AddField(
            model_name="paquete",
            name="modo_disciplinas",
            field=models.CharField(
                choices=[("FIJO", "Fijo"), ("ELEGIBLE", "Elegible")],
                default="ELEGIBLE",
                help_text="FIJO: disciplinas predefinidas. ELEGIBLE: usuario elige entre las permitidas.",
                max_length=20,
                verbose_name="Modo de disciplinas",
            ),
        ),
    ]
