# Generated by Django migration.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inscripciones", "0004_paquete_cantidad_disciplinas_requeridas_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="equipoinscrito",
            name="uq_equipo_inscripcion_disciplina",
        ),
    ]
