# Generated by Django 5.2.12 on 2026-09-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscripciones", "0005_remove_uq_equipo_inscripcion_disciplina"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscripcion",
            name="comprobante_pago",
            field=models.FileField(
                blank=True,
                help_text="Comprobante de pago manual (depósito bancario u otro método)",
                null=True,
                upload_to="inscripciones/comprobantes/",
                verbose_name="Comprobante de pago",
            ),
        ),
    ]
